import { PlanKey } from '../types';

export const ALL_FEATURES = {
    weeklyPlanGenerations: { key: 'weeklyPlanGenerations', text: 'Geração de Plano Semanal', aLaCartePrice: 4.99, aLaCartePackSize: 4 },
    dailyPlanGenerations: { key: 'dailyPlanGenerations', text: 'Geração de Plano Diário', aLaCartePrice: 2.99, aLaCartePackSize: 10 },
    dayRegenerations: { key: 'dayRegenerations', text: 'Regenerar Dia Inteiro', aLaCartePrice: 2.99, aLaCartePackSize: 10 },
    chatImports: { key: 'chatImports', text: 'Importar Plano do Chat', aLaCartePrice: 1.99, aLaCartePackSize: 5 },
    shoppingLists: { key: 'shoppingLists', text: 'Gerar Lista de Compras', aLaCartePrice: 3.99, aLaCartePackSize: 5 },
    recipeSearches: { key: 'recipeSearches', text: 'Receitas Geradas com IA', aLaCartePrice: 4.99, aLaCartePackSize: 20 },
    macroAdjustments: { key: 'macroAdjustments', text: 'Ajustar Macro do Dia', aLaCartePrice: 1.99, aLaCartePackSize: 20 },
    progressAnalyses: { key: 'progressAnalyses', text: 'Análise de Progresso com IA', aLaCartePrice: 4.99, aLaCartePackSize: 5 },
    chatInteractions: { key: 'chatInteractions', text: 'Interações no Chat com IA', aLaCartePrice: 2.99, aLaCartePackSize: 100 },
    mealAnalysesText: { key: 'mealAnalysesText', text: 'Analisar Refeição (Texto)' },
    mealAnalysesImage: { key: 'mealAnalysesImage', text: 'Analisar Refeição (Imagem)', aLaCartePrice: 9.99, aLaCartePackSize: 10 },
    itemSwaps: { key: 'itemSwaps', text: 'Substituir Item / Regenerar Refeição', aLaCartePrice: 1.99, aLaCartePackSize: 20 },
    imageGen: { key: 'imageGen', text: 'Geração de Imagem de Receita', aLaCartePrice: 9.99, aLaCartePackSize: 10 },
    athleteMode: { key: 'athleteMode', text: 'Modo Atleta de Alta Performance' },
    earlyAccess: { key: 'earlyAccess', text: 'Acesso Antecipado a Recursos' },
    prioritySupport: { key: 'prioritySupport', text: 'Suporte Prioritário' },
};

export const PLANS: Record<PlanKey, any> = {
  basic: {
    name: 'Básico',
    price: { monthly: 19.90, annual: 199.90 },
    description: 'Para começar a explorar o poder da IA na sua nutrição.',
    recommended: false,
    features: [
      { ...ALL_FEATURES.weeklyPlanGenerations, limit: 1, period: 'week', value: '1/semana' },
      { ...ALL_FEATURES.dailyPlanGenerations, limit: 2, period: 'day', value: '2/dia' },
      { ...ALL_FEATURES.dayRegenerations, limit: 2, period: 'day', value: '2/dia' },
      { ...ALL_FEATURES.chatImports, limit: 1, period: 'day', value: '1/dia' },
      { ...ALL_FEATURES.shoppingLists, limit: 2, period: 'week', value: '2/semana' },
      { ...ALL_FEATURES.recipeSearches, limit: 15, period: 'week', value: '15/semana' },
      { ...ALL_FEATURES.macroAdjustments, limit: 10, period: 'day', value: '10/dia' },
      { ...ALL_FEATURES.itemSwaps, limit: 15, period: 'day', value: '15/dia' },
      { ...ALL_FEATURES.progressAnalyses, limit: 1, period: 'day', value: '1/dia' },
      { ...ALL_FEATURES.chatInteractions, limit: 50, period: 'day', value: '50/dia' },
      { ...ALL_FEATURES.mealAnalysesText, limit: Infinity, value: 'Ilimitado' },
      { ...ALL_FEATURES.mealAnalysesImage, available: false },
      { ...ALL_FEATURES.imageGen, available: false },
      { ...ALL_FEATURES.athleteMode, available: false },
    ],
  },
  pro: {
    name: 'Pro',
    price: { monthly: 24.90, annual: 249.90 },
    description: 'Recursos ilimitados para transformar sua saúde e performance.',
    recommended: true,
    features: [
      { ...ALL_FEATURES.weeklyPlanGenerations, limit: 4, period: 'week', value: '4/semana' },
      { ...ALL_FEATURES.dailyPlanGenerations, limit: 10, period: 'day', value: '10/dia' },
      { ...ALL_FEATURES.dayRegenerations, limit: 10, period: 'day', value: '10/dia' },
      { ...ALL_FEATURES.chatImports, limit: 10, period: 'day', value: '10/dia' },
      { ...ALL_FEATURES.shoppingLists, limit: Infinity, value: 'Ilimitado' },
      { ...ALL_FEATURES.recipeSearches, limit: 100, period: 'week', value: '100/semana' },
      { ...ALL_FEATURES.macroAdjustments, limit: Infinity, value: 'Ilimitado' },
      { ...ALL_FEATURES.itemSwaps, limit: Infinity, value: 'Ilimitado' },
      { ...ALL_FEATURES.progressAnalyses, limit: 5, period: 'day', value: '5/dia' },
      { ...ALL_FEATURES.chatInteractions, limit: Infinity, value: 'Ilimitado' },
      { ...ALL_FEATURES.mealAnalysesText, limit: Infinity, value: 'Ilimitado' },
      { ...ALL_FEATURES.mealAnalysesImage, limit: 5, period: 'day', value: '5/dia' },
      { ...ALL_FEATURES.imageGen, limit: 5, period: 'week', value: '5/semana' },
      { ...ALL_FEATURES.athleteMode, available: true },
    ],
  },
  premium: {
    name: 'Premium',
    price: { monthly: 77.90, annual: 779.90 },
    description: 'A experiência definitiva com acesso total e benefícios exclusivos.',
    recommended: false,
    features: [
      { ...ALL_FEATURES.weeklyPlanGenerations, limit: Infinity, value: 'Ilimitado' },
      { ...ALL_FEATURES.dailyPlanGenerations, limit: Infinity, value: 'Ilimitado' },
      { ...ALL_FEATURES.dayRegenerations, limit: Infinity, value: 'Ilimitado' },
      { ...ALL_FEATURES.chatImports, limit: Infinity, value: 'Ilimitado' },
      { ...ALL_FEATURES.shoppingLists, limit: Infinity, value: 'Ilimitado' },
      { ...ALL_FEATURES.recipeSearches, limit: Infinity, value: 'Ilimitado' },
      { ...ALL_FEATURES.macroAdjustments, limit: Infinity, value: 'Ilimitado' },
      { ...ALL_FEATURES.itemSwaps, limit: Infinity, value: 'Ilimitado' },
      { ...ALL_FEATURES.progressAnalyses, limit: Infinity, value: 'Ilimitado' },
      { ...ALL_FEATURES.chatInteractions, limit: Infinity, value: 'Ilimitado' },
      { ...ALL_FEATURES.mealAnalysesText, limit: Infinity, value: 'Ilimitado' },
      { ...ALL_FEATURES.mealAnalysesImage, limit: Infinity, value: 'Ilimitado' },
      { ...ALL_FEATURES.imageGen, limit: Infinity, value: 'Ilimitado' },
      { ...ALL_FEATURES.athleteMode, available: true },
      { ...ALL_FEATURES.earlyAccess, available: true },
      { ...ALL_FEATURES.prioritySupport, available: true },
    ],
  },
};
